version: '3'

services:
  hotel-database:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testapp
    ports:
      - "3306:3306"
    volumes:
      - hotel-database-volume:/var/lib/mysql

  admin:
    image: adminer
    ports:
      - "8080:8080"
  
  reservation-api:
    build: src
    command: uvicorn main:app --host 0.0.0.0
    ports:
      - "8008:8000"

volumes:
  hotel-database-volume: